version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  localstack:
    image: localstack/localstack:3.2
    environment:
      - SERVICES=dynamodb,sqs
      - DEFAULT_REGIN=us-east-1
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - ./localstack:/tmp/localstack