version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # Porta para o LocalStack
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock