# Spring
spring.application.name=Consentimento

# Redis
spring.data.redis.host=localstack
spring.data.redis.port=6379

# DynamoDB
aws.dynamodb.endpoint=http://localstack:4566
aws.dynamodb.region=us-east-1
aws.dynamodb.acess-key-id=test
aws.dynamodb.secret-access-key=test

# SQS
aws.sqs.endpoint=http://localhost:4566
aws.sqs.region=us-east-1
aws.sqs.queue=consentimento-inativo-queue

